language: java
jdk:
- openjdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key:
    secure: "TODO: run `travis setup releases` to setup deployment"
  file:
    - build/libs/md*all*.jar
    - build/distributions/md*shadow*.zip
    - build/distributions/md*shadow*.tar
    # list file globs here for deployment
  on:
    repo: gschueler/mdcat
    tags: true
  file_glob: true
  skip_cleanup: true
